version: '3.9'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=acltesting
      - POSTGRES_PASSWORD=123456
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes: 
      - ./data:/var/lib/postgresql/data
      # copy the sql script to create tables
      #- ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
